# =============================================================================
#
# - Copyright (C) 2017     George Li <yongxinl@outlook.com>
#
# - This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# =============================================================================

FROM alpine:3.6
MAINTAINER George Li <yongxinl@outlook.com>

# upload scripts to container unit
COPY assets/ /scripts

RUN set -e; \
    apk add --no-cache bash curl nano tar zip unzip \ 
        git gcc make musl-dev; \
    unzip -o /scripts/dumb-init.zip -d /tmp; \
    cd /tmp/dumb-init; \
    make; \
    cp /tmp/dumb-init/dumb-init /sbin/; \
    mkdir -p /etc/startup; \
    unzip -o /scripts/runit.zip -d /tmp; \
    cd /tmp/runit; \
    make; \
    cp chpst runit runit-init runsv runsvchdir runsvdir sv svlogd utmpset /sbin; \
    mkdir -p /etc/service; \
    rm -rf /tmp/*; \
    apk del --no-cache git gcc make musl-dev zip unzip;

# define default command
CMD ["/sbin/dumb-init", "/sbin/runsvdir", "-P", "/etc/service"]